### ISSUE TITLE
upstream this

### ISSUE THREAD

**Issue by roidelapluie** [n888/prometheus-lightsail-sd#6]
hello, would you be interested in moving this upstream in prometheus/prometheus? thanks!

**Comment by n888** [comment]
Hi @roidelapluie, thanks for reaching out - I am interested and will start working towards a PR this week.

**Comment by roidelapluie** [comment]
I suggest to see if the ec2 SD can be moved to an `amazon` directory and you can register both ec2 and lightsail SD in the same directory (look how we do for zookeeper).

**Comment by n888** [comment]
:tada: https://github.com/prometheus/prometheus/pull/8693

**Comment by roidelapluie** [comment]
Thanks again :)
